server:
  port: 7090
spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bharatvr/JavaSpringCloudEcosystem/tree/master/configFile