eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/databsename
    username: userName
    password: passWord
    driverClassName: org.postgresql.Driver